{% set name = "gimagereader-qt" %}
{% set version = "3.4.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/manisandro/gImageReader/releases/download/v{{ version }}/gimagereader-{{ version }}.tar.xz
  sha256: 8c57a60113b14b9f94dce20a8394a59cb8df2acb57f80d0e5c6f2e31ed5ee2a4

build:
  number: 6
  skip: true  # [not linux]

requirements:
  build:
    - make
    - cmake
    - pkg-config
    - autoconf
    - automake
    - libtool
    - intltool
    - ninja
    - libcap
    - libgomp
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - djvulibre
    - enchant
    - iso-codes
    - libnsl
    - libxmlplusplus
    - libxml2
    - libzip
    - podofo
    - poppler
    - poppler-qt
    - qt-main
    - qtspell
    - quazip
    - sane
    - tesseract
  run:
    - djvulibre
    - enchant
    - iso-codes
    - libnsl
    - libxmlplusplus
    - libxml2
    - libzip
    - podofo
    - poppler
    - poppler-qt
    - qt-main
    - qtspell
    - quazip
    - sane
    - tesseract

test:
  commands:
    - test -f $PREFIX/bin/gimagereader-qt5

about:
  home: https://github.com/manisandro/gImageReader
  license: GPL-3.0-only
  license_family: GPL3
  license_file: COPYING
  summary: gImageReader is a simple Gtk/Qt front-end to tesseract-ocr

extra:
  recipe-maintainers:
    - izahn
